---
- hosts: local

  vars:
    dysk: 'sda'
    montowanie: '/mnt/dysk'
    montowanie_efi: "{{ montowanie }}/boot/efi"
    fs: 'ext4'
    partycja_glowna: 1
    partycja_efi: 1
    partycja_glowna_efi: 2
    efi: nie

  tasks:

    - name: Sprawdzanie  wersji systemu
      fail: msg="SYSTEM LIVE MUSI BYC 64-bitowy"
      when: ansible_architecture != "x86_64"

    - pause:
        prompt: 'PODAJ WERSJE KASY DO INSTALACJI: "xkasnet 2.2.14+ (18) / wpisz numer: 18'
        echo: yes
      register: ubuntu_wer

    - set_fact:
        wzorzecKASY: "kasa_wzor_czysty_{{ ubuntu_wer.user_input }}.04.tar.gz"

    - name: Wykrywam dyski
      set_fact:
        dyski: "{{ dyski | default([]) + [ item.key ] }}"
      no_log: True
      with_dict: "{{ hostvars[inventory_hostname].ansible_devices }}"
      when: item.value.sectors != "0" and item.value.removable == "0" and item.value.host != ""

    - name: WYKRYTE DYSKI
      debug:
        msg: "{{ dyski | list }}"
      when: dyski | length > 1

    - pause:
        prompt: "PODAJ DYSK DO INSTALACJI SYSTEMU: {{ dyski | list }}"
        echo: yes
      register: result
      when: dyski | length > 1

    - set_fact:
        dysk: "{{result.user_input }}"
      when: dyski | length > 1

    - set_fact:
        dysk: "{{ dyski[0] }}"
      when: dyski | length == 1

    - name: Sprawdzanie wybranego dysku
      set_fact:
        OK: 1
      when: dysk == item
      loop: "{{ dyski }}"

    - fail:
        msg: "PODANY DYSK JEST NIEPRAWIDLOWY"
      when: OK | default('0') != 1

    - pause:
        prompt: "CZY INSTALOWAĆ UEFI ? t/n"
        echo: yes
      register: uefi
      when: not ( dysk | regex_search('nvm'))

    - set_fact:
        efi: "tak"
      when: (dysk | regex_search('nvm')) or (uefi.user_input == "t")

    - set_fact:
        partycja_efi: p1
      when: dysk | regex_search('nvm')

    - set_fact:
        partycja_glowna_efi: p2
      when: dysk | regex_search('nvm')

    - name: BOOT EFI
      import_tasks: boot_efi.yml
      when: efi == "tak"

    - name: BOOT bez efi
      import_tasks: boot_bez_efi.yml
      when: efi == "nie"

    - name: instalacja bez EFI
      import_tasks: bez_efi.yml
      when: efi == "nie"

    - name: instalacja EFI
      import_tasks: efi.yml
      when: efi == "tak"

    - name: instalacja kasy
      import_tasks: kasa.yml
      when: ubuntu_wer.user_input == "22"

    - debug:
        msg: "Instalacja zostala zakonczona. Zrestaruj komputer."
